# Generated by Django 5.0 on 2024-01-23 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gnawcontrol',
            name='Global_Nuclei_CoolDown',
            field=models.IntegerField(blank=True, default='4'),
        ),
        migrations.AlterField(
            model_name='gnawcontrol',
            name='Global_Nuclei_RateLimit',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
