# Generated by Django 4.1.7 on 2024-02-06 21:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import recon.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Elevate_Vuln', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256, null=True)),
                ('callbackServer', models.CharField(default='http://127.0.0.1', max_length=2048)),
                ('callbackServerKey', models.CharField(blank=True, max_length=2048)),
                ('request_method', models.CharField(blank=True, max_length=7, null=True)),
                ('payloads', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('postData', models.TextField(blank=True)),
                ('ComplexPathPython', models.TextField(blank=True)),
                ('ComplexAttackPython', models.FileField(blank=True, upload_to=recon.models.user_directory_path)),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, size=None)),
                ('creds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, size=None)),
                ('pathDeveloper', models.TextField(blank=True)),
                ('rawRequest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10240), blank=True, size=None)),
                ('SSL', models.BooleanField(default='False')),
                ('timeout_betweenRequest', models.CharField(blank=True, max_length=10)),
                ('repeatnumb', models.CharField(blank=True, max_length=6)),
                ('redirect', models.BooleanField(default='False')),
                ('matchers_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, size=None)),
                ('matchers_headers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, size=None)),
                ('matchers_bodys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, size=None)),
                ('matchers_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, size=None)),
                ('shodan_query', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, size=None)),
                ('google_dork', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), size=None)),
                ('tcpversioning', models.CharField(blank=True, max_length=2048)),
                ('vulnCard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mantis_record', to='recon.vulncard')),
            ],
        ),
        migrations.DeleteModel(
            name='PythonNuclei',
        ),
    ]
