# Generated by Django 5.0 on 2024-01-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_alter_customers_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnawcontrol',
            name='Global_Nuclei_CoolDown',
            field=models.IntegerField(blank=True, default='4', null=True),
        ),
        migrations.AlterField(
            model_name='gnawcontrol',
            name='Global_Nuclei_RateLimit',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
