# Generated by Django 5.0 on 2024-01-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_alter_customers_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
    ]
